apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: qdrant
  labels:
    app: qdrant
    type: local
spec:
  accessModes:
      - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual